name: CI
on:
  pull_request:
    branches: [integration, laboratory, main]
  push:
    branches: [integration]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
      - name: Build & Test
        run: ./mvnw -B -ntp verify

